kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openebs-local-lvm-pvc
spec:
  storageClassName: openebs-lvmpv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
