apiVersion: v1
kind: Service
metadata:
  name: nacos
  labels:
    app: nacos 
spec:
  type: LoadBalancer
  ports:
    - port: 8848
      name: server
      targetPort: 8848
  selector:
    app: nacos
