kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openebs-jiva-csi-pvc
spec:
  storageClassName: openebs-jiva-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
