# Maintainer: MageEdu <mage@magedu.com>
# Date: 2023-12-10 17:38:00
#
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: propagationpolicy-spread-demo
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: demoapp
  placement:
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      # 基于权重将应用的副本分散至多个集群中
      weightPreference:
        staticWeightList:
          - targetCluster:
              clusterNames:
                - kube02
            weight: 3
          - targetCluster:
              clusterNames:
                - kube03
            weight: 1
        # 使用为集群指定的静态权重
  propagateDeps: true
  # 自动分发依赖到的其它资源对象
