apiVersion: v1
data:
  root.password: bWFnZWR1LmNvbQ==
  wordpress.db: d3BkYg==
  wordpress.password: d3BwYXNz
  wordpress.username: d3B1c2Vy
kind: Secret
metadata:
  creationTimestamp: null
  name: mysql-secret
  namespace: blog
