apiVersion: v1
kind: Pod
metadata:
  name: pod-with-cert-secret
spec:
  containers:
  - name: kubectl
    image: bitnami/kubectl:1.28
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh","-c","sleep 99999"]
    volumeMounts:
    - name: cert
      mountPath: "/certs"
      readOnly: true
  volumes:
  - name: cert
    secret:
      secretName: apiserver-user-kubeadmin-tls
